### ISSUE TITLE
Minor nitpick

### ISSUE THREAD

**Issue by tarjei** [voxpupuli/puppet-prometheus#1]
Hi I would like to suggest that the example config also includes config for a local node_exporter :)

Also - thanks for making this module!

**Comment by brutus333** [comment]
Sure, I am going to change it with the next release. I am planning to add support for push gateway, too.
Stay tuned.

**Comment by tarjei** [comment]
Great, thanks :)

2016-04-12 11:42 GMT+02:00 brutus333 notifications@github.com:

> Sure, I am going to change it with the next release. I am planning to add
> support for push gateway, too.
> Stay tuned.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/brutus333/puppet-prometheus/issues/1#issuecomment-208818818

## 

---

Tarjei Huse
Mobil: 920 63 413

**Comment by William1444** [comment]
Hi there! This module has saved us a tonne of time! 
Have you had any chance to look at push gateway support? I am looking at this myself now, and think I'll need to do it manually for now.

**Comment by brutus333** [comment]
I reached a point when I would like to find some spare time to develop a special module for generic startup scripts templates based on defined resources. Otherwise, the code grows ugly and it is hard to be maintained....

**Comment by TheMeier** [comment]
i think the original issue of providing node_exporter configuration is sufficiently adressed...

**Comment by juniorsysadmin** [comment]
Resolved by a1a64811e1a

**Comment by tarjei** [comment]
Thanks!
