### ISSUE TITLE
Update release on forge.puppetlabs.com

### ISSUE THREAD

**Issue by TheMeier** [voxpupuli/puppet-prometheus#107]
https://forge.puppet.com/puppet/prometheus still shows release  Version 1.0.0 released Mar 27th 2017 

but here https://github.com/voxpupuli/puppet-prometheus/releases there is also v2.0.0 and v3.0.0

**Comment by bastelfreak** [comment]
Hi,
a few of our past releases failed, this got now fixed. I will try to republish them, but this is maybe not possible.

**Comment by bastelfreak** [comment]
That was unexpectly easy. I republished both old releases (2.0.0 and 3.0.0). Another fresh release will come out soon.
