### ISSUE TITLE
Question: is Prometheus 2.0.0 supported?

### ISSUE THREAD

**Issue by jgrumboe** [voxpupuli/puppet-prometheus#110]
Is the new Prometheus version 2.0.0 supported by this module?

**Comment by costela** [comment]
As far as I can see, currently alert and recording rules are not supported (the module uses only the 1.* syntax, which [has been changed for 2.0](https://prometheus.io/blog/2017/06/21/prometheus-20-alpha3-new-rule-format/)). But the rest seems to work, so if you're only using prometheus for graphing, it should work.

**Comment by costela** [comment]
See #120

**Comment by igalic** [comment]
this has been fixed in https://github.com/voxpupuli/puppet-prometheus/pull/127 so i'll close this issue
