### ISSUE TITLE
Error: Could not parse application options: invalid option: --to_yaml

### ISSUE THREAD

**Issue by sathieu** [voxpupuli/puppet-prometheus#118]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby:2.1.5p273
- Distribution: Debian
- Module version: since #101.

## How to reproduce (e.g Puppet code you use)

Use older Puppet agent (we use Puppet master 4.8.2).

## What are you seeing
```
[...]
Info: Loading facts
Error: Could not parse application options: invalid option: --to_yaml
Could not retrieve fact='prometheus_alert_manager_running', resolution='<anonymous>': undefined method `[]' for false:FalseClass
Info: Caching catalog for mynode
[...]
```

## What behaviour did you expect instead

No warning

**Comment by tuxmea** [comment]
Puppet: 3.8.7 is no longer supported. check metadata.json:
`
  "requirements": [
    {
      "name": "puppet",
      "version_requirements": "=> 4.7.1 < 6.0.0"
    }
  ],`

**Comment by tuxmea** [comment]
Can you please check that your agent is really running 3.8.7? That version is very outdated.
Additionally you mentioned puppet master 4.8.2.
The behavior you are describing comes from a fact. Facts are gathered on the agent and are unrelated to the master.
Can you update your agent to also run on 4.8.2?

**Comment by sathieu** [comment]
I known that agent 3.x is not supported. but it was working before.

I can't upgrade the agent to 4.x.

**Comment by tuxmea** [comment]
I suppose that you have to stay with older version of this module which is working on puppet 3. You can not use master branch as this is puppet 4 and later only. @bastelfreak how about your opinion?

**Comment by sathieu** [comment]
The node with agent 3.x is not the one with prometheus installed. Having this fact executed on all nodes is unecessary I think.

**Comment by tuxmea** [comment]
@sathieu can you please check #119 and verify whether this version of the fact fixes your issue?
