### ISSUE TITLE
bug: alert rules are still 1.0 syntax for Prometheus 2

### ISSUE THREAD

**Issue by knackjax** [voxpupuli/puppet-prometheus#120]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)

See templates/alert.epp

## What are you seeing

1.0 syntax

## What behaviour did you expect instead

2.0 yaml syntax

**Comment by tuxmea** [comment]
@knackjax can you provide an example how the alert rules must be for prometheus2? Can you also provide a PR?

**Comment by costela** [comment]
@tuxmea https://prometheus.io/blog/2017/06/21/prometheus-20-alpha3-new-rule-format/

I'm also taking a look at this, but if someone beats me to a PR, all the better! :wink:

**Comment by costela** [comment]
Ideally, we'd support both formats, and maybe also take the chance and fix #69 while we're at it.

**Comment by knackjax** [comment]
I have a hack for this, which basically uses promtool to update to 2.0 syntax. We are just evaluating prometheus for our needs right now if we adopt it we will try to submit a cleaner solution


        exec { "promtool update ${alertfile_name}":
            user        => $user,
            group       => $group,
            command     => "${bin_dir}/promtool update rules ${config_dir}/${alertfile_name}",
            require     => [
                Package[$package_name],
                File["${config_dir}/${alertfile_name}"]
            ],
            unless      => "/usr/bin/test -f ${config_dir}/${alertfile_name}.yml",
            subscribe   => File["${config_dir}/${alertfile_name}"]
        }
        # ensure file was created
        file { "${config_dir}/${alertfile_name}.yml":
            ensure       => 'file',
            owner        => $user,
            group        => $group,
            validate_cmd => "${bin_dir}/promtool check rules ${config_dir}/${alertfile_name}.yml",
        }

**Comment by igalic** [comment]
thanks @jhooyberghs for providing the fix!
