### ISSUE TITLE
Do not manage prometheus.yml

### ISSUE THREAD

**Issue by jamtur01** [voxpupuli/puppet-prometheus#128]
I'd prefer to have the option not to manage `prometheus.yml`.

**Comment by tuxmea** [comment]
@jamtur01 good idea. can you provide a PR?

**Comment by jamtur01** [comment]
@tuxmea I looked when I added the issue but the config is quite messy. I don't much care for the "add blobs of stuff" in manifests model, which is fundamentally not scalable. I actually think it needs a full refactor, for which I don't have time. I've worked around it with a hack currently. :(

**Comment by hooten** [comment]
Looks like https://github.com/voxpupuli/puppet-prometheus/pull/319 resolved this issue

**Comment by TheMeier** [comment]
I agree, with `prometheus::server::manage_config` you can disable the config file and define your own somewhere eles.
