### ISSUE TITLE
Propose to add configuration for http proxy

### ISSUE THREAD

**Issue by weijianwen** [voxpupuli/puppet-prometheus#129]
`puppet-prometheus` downdoads packages directly from the Internet. Unfortunately my hosts are are behind a HTTP proxy thus is always fails when downloading. Since `archive` moduel itself supports `proxy_server` and `proxy_type`, shall I add configuration in `puppet-promethues` to enable HTTP proxy?

**Comment by tuxmea** [comment]
@weijianwen many thanks for this feedback. It would be great if you can do a PR and add optional proxy configuration.

**Comment by joaquin386** [comment]
Same as: https://github.com/voxpupuli/puppet-prometheus/issues/186

**Comment by TheMeier** [comment]
I assume this is fixed in https://github.com/voxpupuli/puppet-prometheus/pull/641
If not please re-open
