### ISSUE TITLE
Facter error on older distributions (Ubuntu Trusty)

### ISSUE THREAD

**Issue by vladgh** [voxpupuli/puppet-prometheus#142]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.3.3
- Ruby: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux] (/opt/puppetlabs/puppet/bin/ruby)
- Distribution: Ubuntu 14.04.5 LTS
- Module version: 4.0.0

## How to reproduce (e.g Puppet code you use)
```
vlad@mini:~ $ /opt/puppetlabs/bin/puppet module install puppet-prometheus --version 4.0.0

vlad@mini:~ $ /opt/puppetlabs/bin/puppet apply --noop -e 'class { "prometheus::node_exporter": version => "0.15.2", }'
```

## What are you seeing
`Error: Facter: error while resolving custom fact "prometheus_alert_manager_running": Could not find init script or upstart conf file for 'alert_manager'`

## What behaviour did you expect instead
No error

## Output log
```
vlad@mini:~ $ /opt/puppetlabs/bin/puppet module install puppet-prometheus --version 4.0.0
Notice: Preparing to install into /home/vlad/.puppetlabs/etc/code/modules ...
Notice: Created target directory /home/vlad/.puppetlabs/etc/code/modules
Notice: Downloading from https://forgeapi.puppet.com ...
Notice: Installing -- do not interrupt ...
/home/vlad/.puppetlabs/etc/code/modules
└─┬ puppet-prometheus (v4.0.0)
  ├── camptocamp-systemd (v1.1.1)
  └─┬ puppet-archive (v2.2.0)
    └── puppetlabs-stdlib (v4.24.0)
vlad@mini:~ $ /opt/puppetlabs/bin/puppet apply --noop -e 'class { "prometheus::node_exporter": version => "0.15.2", }'
Error: Facter: error while resolving custom fact "prometheus_alert_manager_running": Could not find init script or upstart conf file for 'alert_manager'
Notice: Compiled catalog for mini in environment production in 1.17 seconds
Notice: Applied catalog in 0.50 seconds
```

**Comment by tuxmea** [comment]
Many thanks for reporting the issue. Can you please run the following command: `puppet resource service alert_manager --debug`.
For comparision it would be nice to also have the output of the command for an existing service like `puppet resource service ssh --debug` (replace ssh with the name of the ssh service).

**Comment by vladgh** [comment]
Of course. Thank you for looking into this.

[/opt/puppetlabs/bin/puppet resource service alert_manager --color=false --debug  > alert_manager_debug.log 2>&1](https://github.com/voxpupuli/puppet-prometheus/files/1618760/alert_manager_debug.log)

[/opt/puppetlabs/bin/puppet resource service ssh --color=false --debug  > ssh_debug.log 2>&1](https://github.com/voxpupuli/puppet-prometheus/files/1618759/ssh_debug.log)

**Comment by tuxmea** [comment]
Many thanks.
Seems as if alert_manager is not really usable on your system:
```
Debug: /Service[alert_manager]: Provider upstart does not support features flaggable; not managing attribute flags
Debug: Service[alert_manager](provider=upstart): Could not find alert_manager.conf in /etc/init
Debug: Service[alert_manager](provider=upstart): Could not find alert_manager.conf in /etc/init.d
Debug: Service[alert_manager](provider=upstart): Could not find alert_manager in /etc/init
Debug: Service[alert_manager](provider=upstart): Could not find alert_manager in /etc/init.d
Debug: Service[alert_manager](provider=upstart): Could not find alert_manager.sh in /etc/init
Debug: Service[alert_manager](provider=upstart): Could not find alert_manager.sh in /etc/init.d
Error: Could not run: Could not find init script or upstart conf file for 'alert_manager'
```

Is alert_manager installed and running? or not installed at all?

**Comment by vladgh** [comment]
It shouldn't be installed at all; I just installed node exporter:

```
  class { 'prometheus::node_exporter':
    version => '0.15.2',
  }
```

Meanwhile I did some more testing and I think it's more of a puppet issue than the module itself.

Running the same command for a service that should not exist:
`/opt/puppetlabs/bin/puppet resource service madeupservice --debug`

 on a Trusty (non-systemd) fails:
```
Debug: /Service[madeupservice]: Provider upstart does not support features flaggable; not managing attribute flags
Debug: Service[madeupservice](provider=upstart): Could not find madeupservice.conf in /etc/init
Debug: Service[madeupservice](provider=upstart): Could not find madeupservice.conf in /etc/init.d
Debug: Service[madeupservice](provider=upstart): Could not find madeupservice in /etc/init
Debug: Service[madeupservice](provider=upstart): Could not find madeupservice in /etc/init.d
Debug: Service[madeupservice](provider=upstart): Could not find madeupservice.sh in /etc/init
Debug: Service[madeupservice](provider=upstart): Could not find madeupservice.sh in /etc/init.d
Error: Could not run: Could not find init script or upstart conf file for 'madeupservice'
```

while on Xenial returns the correct values:
```
Debug: Executing: '/bin/systemctl is-active madeupservice'
Debug: Executing: '/bin/systemctl is-enabled madeupservice'
service { 'madeupservice':
  ensure => 'stopped',
  enable => 'false',
}
```

**Comment by tuxmea** [comment]
That is great information. We can easily check in the fact for an error from `puppet resource` command. I can work on that within the next few days.

**Comment by vladgh** [comment]
Thank you. I appreciate all your help.
