### ISSUE TITLE
Add support for rabbitmq_exporter

### ISSUE THREAD

**Issue by costela** [voxpupuli/puppet-prometheus#149]
It would be nice to be able to deploy the [rabbitmq_exporter](https://github.com/kbudde/rabbitmq_exporter).

**Comment by tuxmea** [comment]
Are you able to provide a PR? Have a look at the postgres exporter for reference.

**Comment by costela** [comment]
@tuxmea yeah, I was working on it (that's why I also sent #151 😉) but got a bit sidetracked. Should have it in the next couple of days.

**Comment by costela** [comment]
so @tuxmea, finally got around to submitting that PR! PTAL when you have a minute. Thanks!
