### ISSUE TITLE
support alerts manager version >= 0.12.0

### ISSUE THREAD

**Issue by yanivhadad** [voxpupuli/puppet-prometheus#154]
when trying to use version 0.13.0 of alerts manager the service configuration revert to <0.12.0
the problem is in the condition on line 211 of module:
https://github.com/voxpupuli/puppet-prometheus/blob/master/manifests/alertmanager.pp

**Comment by bastelfreak** [comment]
Hi @yanivhadad, thanks for rising up this issue. Are you able to provide a fix for this?

**Comment by TheMeier** [comment]
There is unit and acceptance test wich work with newer version. Also time to rip out support for alertmanager < 0.13.0 I will make an issu for that.
