### ISSUE TITLE
Running dual instances for v1.8 -> 2.1 migration

### ISSUE THREAD

**Issue by ryanash999** [voxpupuli/puppet-prometheus#156]
Based on the best practices documented in the Prometheus migration guide it may be necessary to run two versions in parallel while data history is built. 

https://prometheus.io/docs/prometheus/latest/migration/

Due the puppet constraints, as I understand them, it requires some unique customization to run these two instances.  It would be wonderful if this was a capability of this profile.   Essentially we would want to start the 1.8.x version in a non-scraping mode and v2.1 with a remote_read reference to the old instance running on the same box during a migration period.

**Comment by bastelfreak** [comment]
Hi @ryanash999, thanks for this issue. Are you able to provide a PR that implements this? Or only a little acceptance test that tries to declare prometheus twice so we can see which parts are failling.

**Comment by ryanash999** [comment]
We talked a little more on this yesterday and the easier solution may be to just use the existing 1.8 instance which was laid down by puppet-prometheus with some extra config.  Basically just having the old prometheus.yaml file there and an old serviced file which ensures the old instance is running.  The v2.1 instance would be totally managed with the profile as usual.    This request can probably be remove because others came to this realization before more :)
