### ISSUE TITLE
puppetlabs/stdlib dependency appears to be 4.20.0 and not 4.13.1 

### ISSUE THREAD

**Issue by tullis** [voxpupuli/puppet-prometheus#161]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10 PC1
- Ruby: 2.1.5p273 [x86_64-linux-gnu]
- Distribution: Debian
- Module version: 4.1.0

## How to reproduce (e.g Puppet code you use)

Run puppet agent with version 4.13.1 of stdlib specified in Puppetfile

## What are you seeing

Manifest failure with error:

```
Error: Unknown function: 'to_yaml'. at /etc/puppetlabs/code/environments/prometheus/third_party/prometheus/manifests/alerts.pp:35:30
```

## What behaviour did you expect instead

Manifest compilation.

## Output log

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown function: 'to_yaml'. at /etc/puppetlabs/code/environments/prometheus/third_party/prometheus/manifests/alerts.pp:35:30 on node test
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

## Any additional information you'd like to impart

Updated to version 4.20.0 of stdlib and the manifest compiled.

I checked the changelog of stdlib and the `to_yaml` function appears to have been introduced in version 4.20.0

https://forge.puppet.com/puppetlabs/stdlib/changelog#supported-release-4200

Many thanks for this module.

**Comment by tuxmea** [comment]
Many thanks for reporting the issue.
