### ISSUE TITLE
Allow to configure scrape options by file

### ISSUE THREAD

**Issue by Cosaquee** [voxpupuli/puppet-prometheus#17]
Hi !

Really nice module but right now i do not want to configure the scraping options directly in manifests file. I would like to provide my own `prometheus.yml` file with all the configuration already done. 

As I can see right now you populate `proemtheus.yml` from `prometheus::config` class. What do you thing about one new parameter to `prometheus` class: `scrape_config_file`. If there will be something in this file just drop it in correct place and that is all. If this parameter is empty and `scrape_configs` are set do what you are doing right now.

**Comment by brutus333** [comment]
I was hit by this issue when using the module to upgrade prometheus & friends. scrape_configs is useful only initially or if you plan to configure prometheus only by puppet; which is not always the case.

I agree with your proposal. Can you please make a PR?

**Comment by Cosaquee** [comment]
I have `prometheus.yml` file with more than 10 jobs so it is not convenient to keep it in pp files.

I will fork this and make a PR.

As I can see you still have Ruby 1.9.3 in your Travis tests. From my experience i can say that it is really hard to maintain  Puppet modules with this Ruby version. It is really hard to make sure that dependencies are correct without doing some really ugly things in Gemfile. 

Have you considered dropping support for 1.8.7 and 1.9.3 ?

**Comment by lobeck** [comment]
Isn't this fixed by https://github.com/brutus333/puppet-prometheus/pull/25?

**Comment by Cosaquee** [comment]
@lobeck I looks like #25 is exactly what i wanted. I will close this issue and thanks for you PR : )
