### ISSUE TITLE
alertmanager default inhibit_rules error

### ISSUE THREAD

**Issue by blupman** [voxpupuli/puppet-prometheus#182]
While starting to use alertmanager i noticed the default inhibit_rules cause alertmanager to not start 

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.10
- Ruby: ruby 2.3.3p222
- Distribution: debian/stretch
- Module version: voxpupuli/puppet-prometheus master branch

## How to reproduce (e.g Puppet code you use)

```
  class { '::prometheus::alertmanager':
    version        => '0.14.0',
    install_method => 'url',
    route          => { 'group_by' => [ 'alertname', 'cluster', 'service' ], 'group_wait'=> '30s', 'group_interval'=> '5m', 'repeat_interval'=> '3h', 'receiver'=> 'slack' },
    receivers      => [ { 'name' => 'slack', 'slack_configs'=> [ { 'api_url'=> 'https://hooks.slack.com/services/secret', 'channel' => '#test', 'send_resolved' => true, 'username' => 'username'}] }]
  }
```

(so, not setting inhibit_rules)

## What are you seeing

this causes alertmanager to be installed, but crases after starting, upon investigating i found the error when i started alertmanager by hand.

## What behaviour did you expect instead

an empty running alertmanager

## Output log
```
root@723fefb34eec:/docker/development# alertmanager --config.file /etc/alertmanager/alertmanager.yaml 
level=info ts=2018-04-05T10:32:22.8074184Z caller=main.go:136 msg="Starting Alertmanager" version="(version=0.14.0, branch=HEAD, revision=30af4d051b37ce817ea7e35b56c57a0e2ec9dbb0)"
level=info ts=2018-04-05T10:32:22.8074907Z caller=main.go:137 build_context="(go=go1.9.2, user=root@37b6a49ebba9, date=20180213-08:16:42)"
level=info ts=2018-04-05T10:32:22.8112018Z caller=main.go:275 msg="Loading configuration file" file=/etc/alertmanager/alertmanager.yaml
level=error ts=2018-04-05T10:32:22.8118108Z caller=main.go:278 msg="Loading configuration file failed" file=/etc/alertmanager/alertmanager.yaml err="unknown fields in inhibit rule: severity"
```

## Any additional information you'd like to impart

I have created a [pull request](https://github.com/voxpupuli/puppet-prometheus/pull/181) to generate the same config as params.pp used to make

**Comment by bastelfreak** [comment]
closed by https://github.com/voxpupuli/puppet-prometheus/pull/181
