### ISSUE TITLE
node exporter also installs prometheus server on monitored node

### ISSUE THREAD

**Issue by moon-hawk** [voxpupuli/puppet-prometheus#184]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.10
- Ruby: 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
- Distribution: Debian 9.4 (Stretch)
- Module version: v5.0.1-rc0

## How to reproduce (e.g Puppet code you use)

When we use
```
class { 'prometheus::node_exporter':
    version => '0.14.0',
    ...
}
```
for the monitored nodes, we get also a prometheus server installed on the monitored nodes.

## What are you seeing

promethes server gets installed (Version 1.5.2)
and node exporter gets installed (Version 0.14.0)

## What behaviour did you expect instead

only node exporter gets installed (Version 0.14.0)

## Any additional information you'd like to impart

i think prometheus::node_exporter inherits prometheus
thats why prometheus server gets installed in Version 1,
see your documentation in section "On the server (for prometheus version >= 1.0.0)"

**Comment by blupman** [comment]
I have updated the pull request to remove all inherits from the exports, and replaced the missing data by using lookup(). We're currently running this code on our infra

**Comment by bastelfreak** [comment]
I proposed a patch in https://github.com/voxpupuli/puppet-prometheus/pull/194
