### ISSUE TITLE
Adding a Proxy option

### ISSUE THREAD

**Issue by joaquin386** [voxpupuli/puppet-prometheus#186]
Can not install prometheus if behind a proxy. I need to force the proxy through the ENV variables, after that it works.

Please add a proxy option on the init.pp
 [*proxy*] Comments: Will set the http_proxy and https_proxy to be pass to archive
Optional[String] $proxy,
Optional[String] $proxy_type,

Seems as archive accepts proxy values:
proxy_server: specify a proxy server, with port number if needed. ie: https://example.com:8080.
proxy_type: proxy server type (none|http|https|ftp)
https://forge.puppet.com/puppet/archive

**Comment by joaquin386** [comment]
Was going to create the PR but I see it is already set up on the master branch bu tonly on init.pp

**Comment by bastelfreak** [comment]
Hi @joaquin386, so the options need to be passed to archive? Can you provide a PR for that?

**Comment by joaquin386** [comment]
https://github.com/voxpupuli/puppet-prometheus/pull/263
I have tested only with an http proxy (not https) and the haproxy_exporter and it work (which is what I currently use)

**Comment by dal00** [comment]
Are there any plans on finishing this?

**Comment by bastelfreak** [comment]
@dal00 can you provide a PR for this?

**Comment by dal00** [comment]
There was one already that needed a rebase but it never got finished.

**Comment by chip-b** [comment]
Our environment is behind a proxy as well.  It would be great if proxy options were added.

**Comment by ShaunMaxwell** [comment]
I have created a fresh PR (#596) for this since the old one has gone stale
