### ISSUE TITLE
node_exporterd defaults to older version

### ISSUE THREAD

**Issue by blupman** [voxpupuli/puppet-prometheus#188]
When we decided, we need an optional collector in our node_exporter, it appears the node_exporter.pp creates systemd startup config which is not compatible with node_exporter 0.14.0, which is the default in the current module

Should we upgrade default node_exporter version to 0.15.2 ?

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.10
- Ruby: ruby 2.3.3p222
- Distribution: debian/stretch
- Module version: voxpupuli/puppet-prometheus master branch

## How to reproduce (e.g Puppet code you use)

in hiera:
```
prometheus::node_exporter::collectors_enable:
 - conntrack
 - diskstats
 - entropy
 - systemd
```

## What are you seeing

our systemd config is generated like:
```
[Unit]
Description=Prometheus node_exporter
Wants=basic.target
After=basic.target network.target

[Service]
User=node-exporter
Group=node-exporter
EnvironmentFile=/etc/default/node_exporter
ExecStart=/usr/local/bin/node_exporter \
--collector.conntrack \
--collector.diskstats \
--collector.entropy \
```
this causes node_exporter not to run,

to be installed, but crases after starting, upon investigating i found the error when i started alertmanager by hand.

## What behaviour did you expect instead

a running node_exporter

## Output log

journalctl:
```
May 02 17:15:05 docker-dev-0 node_exporter[2406]: flag provided but not defined: -collector.conntrack

```

**Comment by bastelfreak** [comment]
@blupman thanks for bringing this up. Are you able to provide a patch for this?

**Comment by blupman** [comment]
I'll submit a pull request early next week
