### ISSUE TITLE
Workflow on this module

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-prometheus#21]
Hi @brutus333,

We noticed that you forked your module into our namespace - welcome onboard! We have a few rules here. For example we never push to master and we don't merge our own pull requests. Our docs are written down here: https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli
There is also a CONTRIBUTING.md in each repo: https://github.com/voxpupuli/puppet-prometheus/blob/master/.github/CONTRIBUTING.md

Please read them. There are also all steps documented to do automated releases. Please don't create git tags by hand or do releases with the github UI. Let me know if you have any questions. Maybe you also want to join our IRC channel #voxpupuli on freenode.

Can you tell me why the module got forked and not transferred? A transfer is normally the preferred way. Forks confuse many outside collaborators if they want to contribute patches.

**Comment by rnelson0** [comment]
It appears a "Rebase and Merge" type of merge, rather than either of the Merge Commit types, has been used on PRs #14 and #20. That should probably be disabled in settings if we do not want to use it.

**Comment by brutus333** [comment]
Sorry, I did not intend to break the rules. I've just followed what I understood from the docs. I did not use too much github before in collaborative mode so sincerely I did not know the difference between fork and transfer. Maybe you can add the following to the migration docs: https://help.github.com/articles/about-repository-transfers/
Please tell me what I can do to fix it. 
I'll try also to follow the recommendations from now on as much as I can.
