### ISSUE TITLE
The real_download_url in process-exporter manifest doesn't match to newer versions

### ISSUE THREAD

**Issue by dotSource-GmbH** [voxpupuli/puppet-prometheus#212]
The real_download_url in process-exporter manifest https://github.com/voxpupuli/puppet-prometheus/blob/master/manifests/process_exporter.pp
doesn't match to newer versions of process-exporter!

**process-exporter 0.1**
...${package_name}-${version}.${os}-${arch}.${download_extension}
https://github.com/ncabatoff/process-exporter/releases/download/v0.1.0/process-exporter-0.1.0.linux-amd64.tar.gz

**process-exporter > 0.2**
...${package_name}_${version}_${os}_${arch}.${download_extension}
https://github.com/ncabatoff/process-exporter/releases/download/v0.2.11/process-exporter_0.2.11_linux_amd64.tar.gz

**Comment by bastelfreak** [comment]
ugh what an annoying bug. Thanks for bringing this up @dotSource-GmbH! Are you able to provide a patch for this? Optimal way would be a case statement that sets teh correct url, depending on the provided version.
