### ISSUE TITLE
prometheus::mysqld_exporter::cnf_config_path should not overwrite existing my.cnf file

### ISSUE THREAD

**Issue by dotSource-GmbH** [voxpupuli/puppet-prometheus#226]
The prometheus::mysqld_exporter manifest overwrites an existing my.cnf file with the template. 
I think if file exists then do not overwrite. 
When i configure my prometheus exporters with puppet, i have all my configuration under version control.
So i don't want any passwords in version control systems. But there is actualy no possibility to change the my.cnf password.

**Comment by TheMeier** [comment]
I is a bit unlucky to have the default for `prometheus::mysqld_exporter::cnf_config_path` set to `/etc/.my.cnf`
