### ISSUE TITLE
web.external-url

### ISSUE THREAD

**Issue by sandwitch** [voxpupuli/puppet-prometheus#232]
Hi ,

Is it possible to add the following change some way as a variable?
      # helper variable indicating prometheus version, so we can use on this information in the template
      $prometheus_v2 = true
      $daemon_flags = [
        "--config.file=${prometheus::server::config_dir}/${prometheus::server::configname}",
        "--storage.tsdb.path=${prometheus::server::localstorage}",
        "--storage.tsdb.retention=${prometheus::server::storage_retention}",
        "--web.console.templates=${prometheus::server::shared_dir}/consoles",
        "--web.console.libraries=${prometheus::server::shared_dir}/console_libraries",
        **"--web.external-url=/prometheus",**
      ]
    }

**Comment by bastelfreak** [comment]
hey @sandwitch, thanks for opening the issue. Can you provide a patch for this?

**Comment by tuxmea** [comment]
@sandwitch can ypu please check whether the following settings work:
1. no parameter given:
```
    --web.external-url=''
```
2. parameter given:
```
    --web.external-url='/prometheus'
```
I wonder whether the single quotes are OK.
Otherwise I must rethink the parameter evaluation within the template.

**Comment by sandwitch** [comment]
I' l try tomorrow.Thanks for the input.

**Comment by sandwitch** [comment]
[puppet-prometheus.patch.txt](https://github.com/voxpupuli/puppet-prometheus/files/2187516/puppet-prometheus.patch.txt)
We tried with the changes from tuxmea and it is working as expected. We can change the web.external-url from our hiera data! Looks good to is. If you need more input please let us know.
If you still need the patch is is attached.

**Comment by tuxmea** [comment]
@sandwitch does prometheus still work when you NOT provide hiera data for external web url?

**Comment by tuxmea** [comment]
@sandwitch I just want to be sure that no data or empty string still produces valid config.

```
--web.external-url=''
```

If this is the case, we can merge this PR.
(valid config = properly running prometheus component)

**Comment by sandwitch** [comment]
It is working. See puppet's changes above. Is retarted andere gesteld Prometheus. In case of ' ' IT was not working behind the zentral proxy obvious.  Testing directly on port 9090 worked however. Would be nice of thuis could be merged. Thanks for your work!

**Comment by sandwitch** [comment]
Sorry about the phone translation 😂
