### ISSUE TITLE
Service fails to start under systemd

### ISSUE THREAD

**Issue by slarti5191** [voxpupuli/puppet-prometheus#244]
Quotes in web.external-url are breaking the service with systemd.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.0
- Ruby: 2.0.0p648
- Distribution: CentOS 7
- Module version: 6.1.0

## How to reproduce (e.g Puppet code you use)
Attempt to manage service with systemd and prometheus 2.0.0

## What are you seeing
Service fails to start with this error:

Jul 31 13:53:14 prometheus.example.com prometheus[25352]: parse external URL "'/prometheus'": URL must not begin or end with quotes

Behavior is the same when external.url is not populated.

## What behaviour did you expect instead

Normal service start
## Any additional information you'd like to impart

Fixed with:
```
diff --git a/modules/prometheus/manifests/config.pp b/modules/prometheus/manifests/config.pp
index 9218a41..f198d6c 100644
--- a/modules/prometheus/manifests/config.pp
+++ b/modules/prometheus/manifests/config.pp
@@ -30,7 +30,7 @@ class prometheus::config {
         "--storage.tsdb.retention=${prometheus::server::storage_retention}",
         "--web.console.templates=${prometheus::server::shared_dir}/consoles",
         "--web.console.libraries=${prometheus::server::shared_dir}/console_libraries",
-        "--web.external-url='${prometheus::server::external_url}'",
+        "--web.external-url=${prometheus::server::external_url}",
       ]
     }
```

**Comment by bastelfreak** [comment]
Hey @slarti5191, thanks for rising this issue. Can you provide the puppet code you use to call the module? Do you explicitly set the `$prometheus::server::external_url` parameter?

**Comment by bastelfreak** [comment]
@slarti5191 We just merged https://github.com/voxpupuli/puppet-prometheus/pull/245, can you test if that fixes your issues?
