### ISSUE TITLE
support statsd_exporter >= 0.5.0

### ISSUE THREAD

**Issue by sossickd** [voxpupuli/puppet-prometheus#248]
Add support for statsd_exporter 0.5.0 and the change in the YAML configuration file.

https://github.com/prometheus/statsd_exporter/releases/tag/v0.5.0

The download page also changes to add a v from release 0.4.0 and above.

https://github.com/prometheus/statsd_exporter/releases/download/v0.4.0/statsd_exporter-0.4.0.linux-amd64.tar.gz
https://github.com/prometheus/statsd_exporter/releases/download/0.3.0/statsd_exporter-0.3.0.linux-amd64.tar.gz

**Comment by bastelfreak** [comment]
Hi @sossickd, thanks for bringing this up. Can you provide a PR for this?
