### ISSUE TITLE
prometheus::haproxy_exporter Failing

### ISSUE THREAD

**Issue by joaquin386** [voxpupuli/puppet-prometheus#261]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.0.0
- Ruby: 2.3.3
- Distribution: Comunity Edition
- Module version: 6.1.0

## How to reproduce (e.g Puppet code you use)
  class { 'prometheus::haproxy_exporter':
    version        => '0.9.0',
    cnf_scrape_uri => "http://${::ipaddress}:9000/haproxy?stats;csv",
  }

## What are you seeing
Systemctl start haproxy_exporter -> Doesn't start correctly

## What behaviour did you expect instead
systemctl start haproxy_exporter.service ->  starts correctly

## Output log
Sep 23 11:23:30 ip-10-0-25-10.eu-west-1.compute.internal haproxy_exporter[1801]: haproxy_exporter: error: unknown short flag '-a', try --help
Sep 23 11:23:30 ip-10-0-25-10.eu-west-1.compute.internal systemd[1]: haproxy_exporter.service: main process exited, code=exited, status=1/FAILURE
Sep 23 11:23:30 ip-10-0-25-10.eu-west-1.compute.internal systemd[1]: Unit haproxy_exporter.service entered failed state.
Sep 23 11:23:30 ip-10-0-25-10.eu-west-1.compute.internal systemd[1]: haproxy_exporter.service failed.
Sep 23 11:23:30 ip-10-0-25-10.eu-west-1.compute.internal systemd[1]: haproxy_exporter.service holdoff time over, scheduling restart.
Sep 23 11:23:30 ip-10-0-25-10.eu-west-1.compute.internal systemd[1]: start request repeated too quickly for haproxy_exporter.service
Sep 23 11:23:30 ip-10-0-25-10.eu-west-1.compute.internal systemd[1]: Failed to start Prometheus haproxy_exporter.

## Any additional information you'd like to impart
Problem on https://github.com/voxpupuli/puppet-prometheus/blob/e34a005295d5cf4cc174545aea2728325d2ba0f3/manifests/haproxy_exporter.pp#L107
It should be --haproxy instead of -haproxy

**Comment by bastelfreak** [comment]
Hi @joaquin386, could you provide a PR for this? depending on the haproxy_exporter version the options need to be prefixed with `-` or `--`.

**Comment by joaquin386** [comment]
It is already done here: https://github.com/voxpupuli/puppet-prometheus/pull/179
Closing this issue.
