### ISSUE TITLE
expects a value

### ISSUE THREAD

**Issue by christianreiss** [voxpupuli/puppet-prometheus#262]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 2.6.0
- Ruby: (bundled from puppetlabs) ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
- Distribution: CentOS7
- Module version: 6.2.0

## How to reproduce (e.g Puppet code you use)
Load class via hiera (only)

fqdn.yaml
---
classes:
  - "prometheus"

site.pp:
node default {
  hiera_include("classes")
}

## What are you seeing
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Class[Prometheus]:
  expects a value for parameter 'configname'
  expects a value for parameter 'user'
  expects a value for parameter 'group'
  expects a value for parameter 'extra_groups'
  expects a value for parameter 'bin_dir'
  expects a value for parameter 'shared_dir'
  expects a value for parameter 'install_method'
  expects a value for parameter 'download_url_base'
  expects a value for parameter 'download_extension'
  expects a value for parameter 'package_name'
  expects a value for parameter 'package_ensure'
  expects a value for parameter 'config_dir'
  expects a value for parameter 'localstorage'
  expects a value for parameter 'config_template'
  expects a value for parameter 'config_mode'
  expects a value for parameter 'global_config'
  expects a value for parameter 'rule_files'
  expects a value for parameter 'scrape_configs'
  expects a value for parameter 'remote_read_configs'
  expects a value for parameter 'remote_write_configs'
  expects a value for parameter 'alerts'
  expects a value for parameter 'alert_relabel_config'
  expects a value for parameter 'alertmanagers_config'
  expects a value for parameter 'storage_retention'
  expects a value for parameter 'env_file_path'
  expects a value for parameter 'service_enable'
  expects a value for parameter 'service_ensure'
  expects a value for parameter 'manage_service'
  expects a value for parameter 'restart_on_change'
  expects a value for parameter 'init_style'
  expects a value for parameter 'extra_options'
  expects a value for parameter 'download_url'
  expects a value for parameter 'arch'
  expects a value for parameter 'manage_group'
  expects a value for parameter 'purge_config_dir'
  expects a value for parameter 'manage_user' at /etc/puppetlabs/code/environments/production/site.pp:2:3

## What behaviour did you expect instead
Deployment of a standard, albeit empty Prometheus Server.

## Any additional information you'd like to impart
As you can see from the node yaml file I tried loading "prometheus" solo, "prometheus::server" solo and a combination of both. The same issue arises with launching a client.

**Comment by tuxmea** [comment]
Can you please upgrade to a newer Puppet version like 5.5 or even 6.0?
The module uses data in modules (see hiera.yaml file in module base directory) which has been introduced in Puppet 4.9.

**Comment by bastelfreak** [comment]
You don't actually run Puppet 2.6, do you? This module requires at least 4.10 to work without issues.

**Comment by vladdoster** [comment]
@christianreiss How did you resolve this issue? I am having same issue using ElasticSearch...

**Comment by christianreiss** [comment]
I upgraded to current Puppet. It was an ancient-old puppetserver and code.
