### ISSUE TITLE
Unable to force arch for installing exporter

### ISSUE THREAD

**Issue by defenestration** [voxpupuli/puppet-prometheus#265]
Trying to run node_exporter on an RPI 1. There are releases for it here: https://github.com/prometheus/node_exporter/releases (the armv6 in this case). However i seem unable to force the arch for the module  using hiera `prometheus::node_exporter::arch` since in init.pp it seems to force one of the main arches there. 

[root@dns-pi ~]# cat /proc/device-tree/model
Raspberry Pi Model B Rev 2

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.2 (from raspbian repositories)
- Ruby: ruby 2.3.3p222
- Distribution:   Raspbian GNU/Linux 9.4 (stretch)
- Module version: 6.2

## How to reproduce (e.g Puppet code you use)
classes:
  - prometheus::node_exporter

prometheus::node_exporter::arch: armv6
prometheus::node_exporter::download_url: https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-armv6.tar.gz

## What are you seeing
 Evaluation Error: Error while evaluating a Function Call, Unsupported kernel architecture: armv6l at /etc/puppetlabs/code/environments/production/modules/prometheus/manifests/init.pp:189:7 on node dns-pi

## What behaviour did you expect instead
installation of node_exporter

## Any additional information you'd like to impart

Realize it is a pretty fringe case, sorry bout that. Probably simple to add? but not sure how other services would be affected.  I was surprised node_exporter has a few arm releases actually.

**Comment by bastelfreak** [comment]
Hi @defenestration, thanks for bringing this up. Are you able to provide a patch for this? I'm happy to review and merge it.
