### ISSUE TITLE
Pupppet sysv fails due to -log.format option

### ISSUE THREAD

**Issue by defenestration** [voxpupuli/puppet-prometheus#268]
It seems an old option -log.format for prometheus server was removed and prevents the server from starting up with newer prometheus versions (we're using 2.4.3) when using older Sysv init scripts on at least CentOS6. 

This seems to be the affected line and removing -log.format and parameters seem to work. 
https://github.com/voxpupuli/puppet-prometheus/blob/master/templates/prometheus.sysv.erb#L54

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10
- Ruby: ruby 1.8.7
- Distribution:  CentOS release 6.10 (Final)
- Module version: 6.3.0

## How to reproduce (e.g Puppet code you use)
Use puppet::server class on CentOs6 or sysv class with latest prometheus server version.

## What are you seeing
Prometheus fails to start.

## What behaviour did you expect instead
Prometheus starts and runs.

## Output log
```
[root@statsd.dev /var/log]# service prometheus start
Starting prometheus: 
[root@statsd.dev /var/log]# Error parsing commandline arguments: unknown short flag '-l'
prometheus: error: unknown short flag '-l'
```

## Any additional information you'd like to impart
Looks like this is the issue here. 
https://github.com/voxpupuli/puppet-prometheus/blob/master/templates/prometheus.sysv.erb#L54

Didn't have this issue on systemd startup scripts on Centos7.

**Comment by bastelfreak** [comment]
Hi @defenestration, could you provide a PR for this? it basically requires a switch to check for the prometheus version and afterwards use the long- or the short option.

**Comment by defenestration** [comment]
I added additional commits to resolve the Travis build errors, i seem unable to comment on the PR for some reason though.
