### ISSUE TITLE
alertmanager systemd service doesnt start

### ISSUE THREAD

**Issue by attachmentgenie** [voxpupuli/puppet-prometheus#28]
the binary is now called alertmanager the systemd template is hardcoded to alert_manager

**Comment by brutus333** [comment]
Can you please tell the version of alertmanager used?

**Comment by attachmentgenie** [comment]
0.5.0 and 0.5.1. 
I just went back as far as the 0.0.1 release and it seems that the binary has always been called alertmanager.

**Comment by brutus333** [comment]
I've checked and, indeed, the entry in systemd is /usr/local/bin/alert_manager which is a symbolic link to the /opt/staging/alertmanager-${version}.linux-amd64/alertmanager
I agree that maybe the name of the link should be alertmanager as well, but the program should start regardless of the link name. 
Can you please double check the error?

**Comment by attachmentgenie** [comment]
yup that works.

however, when you package the tar yourself,  you end up with the alertmanager binary and no symlink.
Which requires you to rename the binary during the packaging process, which caused me to notice this problem

**Comment by attachmentgenie** [comment]
this problem has been fixed in the 0.2.0 release
