### ISSUE TITLE
apache_exporter unable to contact apache on Debian 7

### ISSUE THREAD

**Issue by ntesteca** [voxpupuli/puppet-prometheus#296]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet-agent 5.5.1-1wheezy
- Ruby: ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
- Distribution: Debian GNU/Linux 7.8 (wheezy)
- Module version: master (492d18f876fa11c051cea4ceee5bf15a9f8e94e0)

## How to reproduce (e.g Puppet code you use)
Just install the apache_exporter on Debian 7 with Hiera

```
---
classes:
  - prometheus::apache_exporter

prometheus::apache_exporter::version: '0.5.0'
```

## What are you seeing

The `DAEMON_ARGS` line in `/etc/init.d/apache_exporter` is messed up (notice the trailing space too).

```
...
DAEMON_ARGS=-scrape_uri\ \"http://localhost/server-status\?auto\"\ 
...
```

The exporter starts but is unable to contact the Apache server. No traffic seen with `tcpdump`.

## What behaviour did you expect instead

A clean line like `DAEMON_ARGS="-scrape_uri http://localhost/server-status?auto"`

## Output log

`apache_up 0` when calling the metrics.

## Any additional information you'd like to impart

`apache_up 1` with the corrected line.

**Comment by bastelfreak** [comment]
Hi @ntesteca, thanks for this issue. I need to say that we don't support Debian 7 anymore, but this doesn't look like a Debian specific issue. Are you able to provide a patch for this?

**Comment by ntesteca** [comment]
We'll see :)

Further investigation: protected the quotes comes from the use of `Shellwords.escape(@options)` in the daemon template.

Affected templates are `debian`, `sles`, `sysv`. Other templates use `<% for option in Shellwords.split(@options) %>` that does not keep quotes after splitting ([see](https://ruby-doc.org/stdlib-2.6/libdoc/shellwords/rdoc/Shellwords.html#method-c-shellsplit)).

On faulty templates, `\"http://localhost/server-status?auto\"` is passed as an argument. The exporter is unable to parse this as an uri.

Log from the exporter:
```Error scraping apache: parse \"http://localhost/server-status?auto\" : first path segment in URL cannot contain colon```
