### ISSUE TITLE
Install Promtool

### ISSUE THREAD

**Issue by lswith** [voxpupuli/puppet-prometheus#31]
We should install the promtool so that configuration can be checked before reloading the service.

```
./promtool -help
usage: promtool <command> [<args>]

Available commands:
  check-config    validate configuration files for correctness
  check-rules     validate rule files for correctness
  help            prints this help text
  version         print the version of this binary
```

**Comment by brutus333** [comment]
Only a link should be sufficient since the promtool is already in the prometheus binary distribution. On my systems I found it on /opt/staging/prometheus-${version}.linux-amd64/

**Comment by lswith** [comment]
that is correct. I was thinking more if we should run it before we restart the service?

**Comment by brutus333** [comment]
I believe we can run it before reloading or restarting the service. It may be a good idea. However, it will complicate a bit the startup scripts.
