### ISSUE TITLE
Puppetforge not being updated

### ISSUE THREAD

**Issue by hatvik** [voxpupuli/puppet-prometheus#320]
Please update https://forge.puppet.com/puppet/prometheus
Its version 6.40 from Oct 2018 and missing many OS and arch fixes.  

Thanks!

**Comment by rwaffen** [comment]
Bumps. Can we haz a new version, plz? :)

**Comment by alexjfisher** [comment]
Closing this as there have been new releases recently (and I plan another one very soon)
