### ISSUE TITLE
What's the difference between this repository and `puppet-prometheus2`

### ISSUE THREAD

**Issue by joshuaspence** [voxpupuli/puppet-prometheus#35]
We had our `Puppetfile` pointing to the `puppet3` branch of this repository, but it seems that this branch no longer exists. The branch does exist, however, in https://github.com/bastelfreak/puppet-prometheus2. What is the difference between this repository and https://github.com/bastelfreak/puppet-prometheus2?

**Comment by rendhalver** [comment]
It seems that bastelfreak/puppet-prometheus2 is the parent of this module.
It also seems that has had 34 commits since this fork was created so it seems it needs updating. unless these two modules are diverging.
Can someone who is looking after this confirm what is actually happening here?

**Comment by vicfl** [comment]
+1 to ^

**Comment by tuxmea** [comment]
@bastelfreak what is the state of your prometheus module? Should people use the voxpupuli one or yours?

**Comment by bastelfreak** [comment]
Hey everybody. Sorry for the confusion. The original repo got forked into our namespace and not migrated. We tried to fix that but failed, so one version ended up in my namespace. The voxpupuli one is up2date and under active development. We could switch the fork state and make the voxpupuli one the upstream repo and mine the fork, and delete the fork afterwards, but that would drop a lot of history. We probably have to keep it as is.

**Comment by tuxmea** [comment]
@bastelfreak thank you for clarification. Maybe you can add a deprecation note to your fork. I would try to not drop the history.

**Comment by tuxmea** [comment]
@joshuaspence has your question been answered so we can close this issue?

**Comment by joshuaspence** [comment]
Yes it does, thanks
