### ISSUE TITLE
Running puppet restarts service

### ISSUE THREAD

**Issue by nikosmeds** [voxpupuli/puppet-prometheus#37]
Changes to configuration or alert rules results in the Prometheus service restarting.

This is regularly leading to `crash-recovery` mode on Prometheus. Often sending `kill -HUP` to reload the service would be sufficient. Is this a change you'd be okay making?

**Comment by vide** [comment]
Although with current master, this module already reloads config on change, I've implemented a finer control on it with #43

**Comment by TheMeier** [comment]
fixed? close?

**Comment by juniorsysadmin** [comment]
Fixed by #43
