### ISSUE TITLE
Prometheus daemon is not restarting when command-line arguments are changed

### ISSUE THREAD

**Issue by sharadgaur** [voxpupuli/puppet-prometheus#382]
Adding or removing any command-line argument to Prometheus class does not trigger daemon restart.

```
class { 'prometheus':
    configname               => 'prometheus.yml',
    localstorage             => $storage_path,
    manage_user              => false,
    manage_group             => false,
    external_url             => "https://prometheus.test.fake.dns.org",
...
  }

```
In this case, `external_url` is a command-line argument to Prometheus

**Comment by alexjfisher** [comment]
I *think* this is only an issue with systemd.

https://github.com/voxpupuli/puppet-prometheus/blob/0c5e1a11efa6d1609549f51060d005a31a536d32/manifests/config.pp#L160-L162 should be defaulting the `notify` parameter of all file resources in config.pp
The idea is that some file resources can then notify `prometheus::service_reload` instead.

Using resource defaults like this is not recommended.  'Area of effect' can be confusing and cause unintentional results.  See https://puppet.com/docs/puppet/5.5/lang_defaults.html#behavior

As for systemd...
https://github.com/voxpupuli/puppet-prometheus/blob/0c5e1a11efa6d1609549f51060d005a31a536d32/manifests/config.pp#L163 hasn't done anything for about 2 years.  The variable is not used and the Exec referenced doesn't exist either.

**Comment by sharadgaur** [comment]
Should I remove the
```
File { 
   notify => Class['prometheus::run_service'], 
 } 
```


from `config.pp` and make systemd config to use `$systemd_notify` variable? I really don't want to use `Exec`. 
If you don't mind we can get rid of `$system_notify`
