### ISSUE TITLE
Promxy

### ISSUE THREAD

**Issue by thde** [voxpupuli/puppet-prometheus#423]
Would you be interested to have a class in this repository to install and configure Promxy (https://github.com/jacksontj/promxy)? 

If you don't know what it does:

> Promxy is a prometheus proxy that makes many shards of prometheus appear as a single API endpoint to the user. This significantly simplifies operations and use of prometheus at scale (when you have more than one prometheus host). Promxy delivers this unified access endpoint without requiring any sidecars, custom-builds, or other changes to your prometheus infrastructure.

It's also a single binary deployment similar to Prometheus / Alertmanager. So if you think it makes sense that the prometheus class is also able to install Promxy I'd be glad to contribute.

**Comment by anarcat** [comment]
this module is already very loaded: it deploys a lot of different tools, not only the prometheus server, but also a plethora of exporters... we've been thinking about splitting the exporters out, actually, so I'm doubtful we'd include a new project here as well.

i'm sure we'd be happy to host it as a separate module under the voxpupuli umbrella, that said...

**Comment by TheMeier** [comment]
I also would prefer a separate module
I close this for now, please feel free to re-open
