### ISSUE TITLE
Apache Exporter 0.8.0+ uses `--` as argument prefix

### ISSUE THREAD

**Issue by krische** [voxpupuli/puppet-prometheus#442]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: N/A
- Ruby: N/A
- Distribution: N/A
- Module version: `8.3.0`

## How to reproduce (e.g Puppet code you use)
```puppet
class { 'prometheus::apache_exporter':
  version: '0.8.0',
}
```
## What are you seeing
It looks like version [0.8.0 of Apache Exporter](https://github.com/Lusitaniae/apache_exporter/blob/v0.8.0/README.md) now uses `--` as the argument prefix instead of `-`. Specifying the scrape URI with `-scrape_uri` will result in an error `apache_exporter: error: unknown short flag '-s', try --help`.
## What behaviour did you expect instead
The `prometheus::apache_exporter` should use a version comparison to determine if needs `--` or `-`. For example:
```puppet
if versioncmp($version, '0.8.0') < 0 {
  $options = "-scrape_uri \"${scrape_uri}\" ${extra_options}"
} else {
  $options = "--scrape_uri \"${scrape_uri}\" ${extra_options}"
}
```

**Comment by bastelfreak** [comment]
@krische thanks for raising the issue. could you provide a patch for this?
