### ISSUE TITLE
config.pp does not honor $prometheus::purge_config_dir value

### ISSUE THREAD

**Issue by paxri01** [voxpupuli/puppet-prometheus#460]
Currently this module purges any scrape configs within /etc/prometheus/file_sd_config.d directory, no matter what value is assigned to $prometheus::purge_config_dir.  I would expect this to not be the case.

```
225   # TODO: promtool currently does not support checking the syntax of file_sd_config "includes".
226   # Ideally we'd check them the same way the other config files are checked.
227   file { "${prometheus::config_dir}/file_sd_config.d":
228     ensure  => directory,
229     group   => $prometheus::server::group,
230     purge   => true,
231     recurse => true,
232     notify  => Class['prometheus::service_reload'], # After purging, a reload is needed
233   }

```

Proposed change:
`230     purge   => $prometheus::purge_config_dir,`

We are collecting puppetdb resources to generate targets.json and would like to have it stick around awhile :)

Thanks

**Comment by ghoneycutt** [comment]
@paxri01 Could you please submit a pull request? You can do this from the browser.
