### ISSUE TITLE
Tag 1.0.0

### ISSUE THREAD

**Issue by gbloquel** [voxpupuli/puppet-prometheus#47]
Hi all,

The version 1.0.0 seems to be released on March 27th 2017.
Could you tag this version ?

Best regards.

**Comment by TheMeier** [comment]
shoud be fixed ..

https://github.com/voxpupuli/puppet-prometheus/releases/tag/1.0.0

**Comment by bastelfreak** [comment]
Hi @gbloquel, we had some issues with the git repo for multiple reasons. This is now fixed and up2date versions are published to the forge.
