### ISSUE TITLE
scrape_job exported resources are ignoring custom collect dir

### ISSUE THREAD

**Issue by ndelic0** [voxpupuli/puppet-prometheus#490]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.4.2
- Ruby: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
- Distribution:  CentOS Linux release 7.8.2003 (Core)
- Module version: 9.1.0

## How to reproduce (e.g Puppet code you use)
In profile we're exporting scrape_jobs 
```puppet 
$scrape_job_labels = { 'alias' => $::facts['fqdn'] }
@@prometheus::scrape_job { "${::facts['fqdn']}_${_port}":
  job_name    => $name,
  targets     => ["${::facts['fqdn']}:9100"],
  collect_dir => '/srv/prometheus/file_sd_config.d',
  labels      => $scrape_job_labels,
  tag         => $_tag,
}
```

In server profile these resources are collected with :
```puppet 
Prometheus::Scrape_job <<| job_name == $job_name |>> {
  collect_dir => '/srv/prometheus/file_sd_config.d/',
  notify      => Class['::prometheus::service_reload'],
  tag         => $_tag
}
```

## What are you seeing
File configs are created in `/etc/prometheus/file_sd_config.d/`
## What behaviour did you expect instead
File configs are created in `/srv/prometheus/file_sd_config.d/`

**Comment by towo** [comment]
@ndelic0 Having a quick look at the code, I can't see any particular reason why this definition would be ignored. Do you have some leftover code somewhere else saving to the spot? Is it *only* appearing in `/etc/prometheus/file_sd_config.d` - and aren't the files maybe just leftovers from a previous change?

**Comment by ndelic0** [comment]
@towo Thanks for looking into this. Solved the problem with refactoring the profile. Basically replacing class { 'prometheus::server'} call with main class class { 'prometheus': }. Missed this issue https://github.com/voxpupuli/puppet-prometheus/issues/208. Maybe this is worth documenting.

**Comment by towo** [comment]
We're considering refactoring the module entirely with regard to the server class, thanks for the input. :+1:
