### ISSUE TITLE
Prometheus Logging to file

### ISSUE THREAD

**Issue by lswith** [voxpupuli/puppet-prometheus#5]
I would like to make sure the stdout of prometheus is logged to a file. I would like this done on the Debian version of this module.

**Comment by lobeck** [comment]
It's already there on Ubuntu and i guess on Debian too: `/var/log/upstart/prometheus.log` and `/var/log/upstart/alert_manager.log`

**Comment by dev-e** [comment]
Hi! I am using 7.0.0 version of the module and there is no `/var/log/upstart` directory on my Ubuntu host. So where prometheus logs are located?
