### ISSUE TITLE
Change Prometheus port

### ISSUE THREAD

**Issue by Cosaquee** [voxpupuli/puppet-prometheus#52]
Hi!

Is there any option to change the Prometheus port to something different than 9090? I cannot see such options anywhere in the code, but maybe it is buried somewhere. I can make PR and add this possibility to specify a port, it this is not a problem.

**Comment by tuxmea** [comment]
According to [google groups](https://groups.google.com/forum/#!topic/prometheus-users/vX5XAgfGjp4) this is possible on CLI when starting prometheus: `--web.listen-address="0.0.0.0:9091"`

I assume that this setting must be placed into the sysvinit, systemd, upstart scripts.

**Comment by bastelfreak** [comment]
Hi @Cosaquee, thanks for rising this issue. Are you able to provide a pull request which adds this functionality?

**Comment by Cosaquee** [comment]
@bastelfreak, sure. :)

**Comment by tuxmea** [comment]
I wonder whether this is already done and just needs data for extra_options parameter?

**Comment by Cosaquee** [comment]
As far as I can see there is no such param that can be set. Probably we can set it in extra_options but I thing that explicit variable would be better. My question is if we want to provide something like `host` and `port` with defaults `0.0.0.0` and `9090` or just port?

**Comment by tuxmea** [comment]
I would go for `host` and `port`
