### ISSUE TITLE
Allow environment variables for blackbox exporter daemon

### ISSUE THREAD

**Issue by jograb** [voxpupuli/puppet-prometheus#535]
I want to set environment variables for the blackbox exporter.
The reason is that I would like to set `SSL_CERT_FILE` or `SSL_CERT_DIR`. :-)

**Comment by TheMeier** [comment]
@jograb willing to finish this up?

**Comment by jograb** [comment]
checks passed, https://github.com/voxpupuli/puppet-prometheus/pull/536 should be fine and can be merged ✅😊
