### ISSUE TITLE
what's the way to define rules in separate file under prometheus rules directory?

### ISSUE THREAD

**Issue by dthpulse** [voxpupuli/puppet-prometheus#537]
I'm looking for the way scrape rules to separate files under `/etc/prometheus/rules` directory. Didn't find the way with this module. Is it possible?
Thanks

**Comment by TheMeier** [comment]
@dthpulse do you mean scrape configs or alert/recording-rules?

**Comment by TheMeier** [comment]
Closing due to lack of feedback. Feel free to re-open, possible with some more context.
