### ISSUE TITLE
Unable to use this module on fresh alert manager instances

### ISSUE THREAD

**Issue by scottybrisbane** [voxpupuli/puppet-prometheus#55]
In the `alertmanager.pp` manifests there is a service resource that instructs puppet to stop the `alert_manager` service if it is running, since the service has been renamed. This works fine on an old instance that has the `alert_manager` service, but breaks down on new instances that have no such service. I am seeing the following error on a fresh instance that attempts to start the alertmanager:
```
/Stage[main]/Prometheus::Alertmanager/Service[alert_manager]) Could not evaluate: Could not find init script or upstart conf file for 'alert_manager'
```

https://github.com/voxpupuli/puppet-prometheus/blob/56dbfab66f39299ff5a6b620d0224e127c3a53d8/manifests/alertmanager.pp#L205-L207

**Comment by skarip** [comment]
seeing the same thing -- any planned fix?

**Comment by bastelfreak** [comment]
Hi @scottybrisbane and @skarip, is one of you able to provide a patch for this?

**Comment by tuxmea** [comment]
Possible solution (please provide feedback):
- providing a fact which checks whether alert_manager is running
- make the service resource depending on fact result
