### ISSUE TITLE
conflict with camptocamp-systemd latest  release 3.0.0

### ISSUE THREAD

**Issue by raman1236** [voxpupuli/puppet-prometheus#560]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 
- Ruby:
- Distribution:
- Module version: 11.2.0

## How to reproduce (e.g Puppet code you use)
Update Puppet module camptocamp-systemd to latest release 3.0.0

## What are you seeing
`Error: Could not find resource 'Class[Systemd::Systemctl::Daemon_reload]' for relationship on 'Service[node_exporter]'`

'Class[Systemd::Systemctl::Daemon_reload]' is removed in camptocamp-systemd to latest release 3.0.0
Fix: have to remove "Class[Systemd::Systemctl::Daemon_reload]" reference from puppet-prometheus module 

## What behaviour did you expect instead
compile with out error 

## Output log
`Error: Could not find resource 'Class[Systemd::Systemctl::Daemon_reload]' for relationship on 'Service[node_exporter]'`

**Comment by rsynnest** [comment]
Further discussion in https://github.com/voxpupuli/puppet-systemd/issues/190 (camptocamp-systemd was replaced by voxpupuli/puppet-systemd)

**Comment by rsynnest** [comment]
Daemon_reload was removed in https://github.com/voxpupuli/puppet-systemd/commit/97dd16fa32886b5b0f77a6f38a4953d4c1511c0e when they dropped support for Puppet 4 and 5. Puppet 6 handles daemon reloads automatically per [PUP-3483](https://tickets.puppetlabs.com/browse/PUP-3483).

You did not provide your Puppet version, but mine was 5.5, so rolling back prometheus module to appropriate version fixerd the issue (Latest puppet-prometheus 12.1.1 requires Puppet >= 6.1.0)
