### ISSUE TITLE
postgres_exporter 0.10.0 cannot be downloaded

### ISSUE THREAD

**Issue by reini-1** [voxpupuli/puppet-prometheus#584]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.24.0
- Ruby:
- Distribution: Debian
- Module version: latest 12.1.1

## How to reproduce (e.g Puppet code you use)
Set version of postgres_exporter to 0.10.0

## What are you seeing
The latest version of postgres_exporter cannot be downloaded as the url has changed.

https://github.com/wrouesnel/postgres_exporter/releases/download/v0.10.0/postgres_exporter_v0.10.0_linux-amd64.tar.gz
vs.
https://github.com/prometheus-community/postgres_exporter/releases/download/v0.10.0/postgres_exporter-0.10.0.linux-amd64.tar.gz

It is now in the prometheus-community repo, "v" before version in filename is gone, "\_" (underline) before version is now "-" (dash) and "\_" (underline) after version is now a "." (dot).

I think [download_url_base](https://github.com/voxpupuli/puppet-prometheus/blob/master/data/defaults.yaml#L252) in data/defaults.yaml and [$real_download_url](https://github.com/voxpupuli/puppet-prometheus/blob/master/manifests/postgres_exporter.pp#L95) in manifests/postgres_exporter.pp must be changed.

Maybe a distinction between old versions an new (0.9.0+) is necessary.

## What behaviour did you expect instead
The new version should be downloaded.

## Output log
```log
Error: Execution of '/usr/bin/curl https://github.com/wrouesnel/postgres_exporter/releases/download/v0.10.0/postgres_exporter_v0.10.0_linux-amd64.tar.gz -o /tmp/postgres_exporter-0.
10.0.tar.gz_20211001-24770-xvlo91 -fsSLg --max-redirs 5' returned 22: curl: (22) The requested URL returned error: 404
Error: /Stage[main]/Prometheus::Postgres_exporter/Archive[/tmp/postgres_exporter-0.10.0.tar.gz]/ensure: change from 'absent' to 'present' failed: Execution of '/usr/bin/curl https:/
/github.com/wrouesnel/postgres_exporter/releases/download/v0.10.0/postgres_exporter_v0.10.0_linux-amd64.tar.gz -o /tmp/postgres_exporter-0.10.0.tar.gz_20211001-24770-xvlo91 -fsSLg -
-max-redirs 5' returned 22: curl: (22) The requested URL returned error: 404
Notice: /Stage[main]/Prometheus::Postgres_exporter/File[/usr/local/bin/postgres_exporter]: Dependency Archive[/tmp/postgres_exporter-0.10.0.tar.gz] has failures: true
Warning: /Stage[main]/Prometheus::Postgres_exporter/File[/usr/local/bin/postgres_exporter]: Skipping because of failed dependencies
Warning: /Stage[main]/Prometheus::Postgres_exporter/Prometheus::Daemon[postgres_exporter]/Group[postgres-exporter]: Skipping because of failed dependencies
Warning: /Stage[main]/Prometheus::Postgres_exporter/Prometheus::Daemon[postgres_exporter]/User[postgres-exporter]: Skipping because of failed dependencies
Warning: /Stage[main]/Aida::Postgresql::Postgres_exporter/File[/etc/postgres_exporter]: Skipping because of failed dependencies
Warning: /Stage[main]/Aida::Postgresql::Postgres_exporter/File[/etc/postgres_exporter/queries.yaml]: Skipping because of failed dependencies
Warning: /Stage[main]/Prometheus::Postgres_exporter/Prometheus::Daemon[postgres_exporter]/File[/etc/default/postgres_exporter]: Skipping because of failed dependencies
Warning: /Stage[main]/Prometheus::Postgres_exporter/Prometheus::Daemon[postgres_exporter]/Systemd::Unit_file[postgres_exporter.service]/File[/etc/systemd/system/postgres_exporter.se
rvice]: Skipping because of failed dependencies
Warning: /Stage[main]/Prometheus::Postgres_exporter/Prometheus::Daemon[postgres_exporter]/Service[postgres_exporter]: Skipping because of failed dependencies
```

**Comment by donjuanmon** [comment]
Had same problem, defining this worked for download:

```puppet
class { 'prometheus::postgres_exporter':
  download_url    => 'https://github.com/prometheus-community/postgres_exporter/releases/download/v0.10.0/postgres_exporter-0.10.0.linux-amd64.tar.gz',
  version         => '0.10.0',
}
```

**Comment by reini-1** [comment]
any progress on this?

**Comment by reini-1** [comment]
any thing new here?

**Comment by smortex** [comment]
Have you considered opening a Pull Request (PR) to add your change :wink:? This look like a perfect enhancement for a first-time contributor!

If you do not know how to start, here is a quite complete guide about the process of contributing to projects on GitHub:
https://dataschool.io/how-to-contribute-on-github

In any case, do not feel scared: we are here to help!

**Comment by reini-1** [comment]
I will try ...
