### ISSUE TITLE
Use `systemctl` instead of `service` in Arch Linux

### ISSUE THREAD

**Issue by hashworks** [voxpupuli/puppet-prometheus#612]
Using the module on Arch Linux results in `service reload` calls which are not supported in Arch.

## How to reproduce (e.g Puppet code you use)

```
class profiles::prometheus () {
  include prometheus::server
}
```

## What are you seeing

```
Error: /Stage[main]/Prometheus::Service_reload/Exec[prometheus-reload]: Failed to call refresh: Could not find command 'servi
ce'
Error: /Stage[main]/Prometheus::Service_reload/Exec[prometheus-reload]: Could not find command 'service'
```

## What behaviour did you expect instead

Uses `systemctl reload` on Arch Linux.

**Comment by TheMeier** [comment]
IMHO this is already fixed. Please re-open if i am wrong.
