### ISSUE TITLE
Prometheus service wont run if installed from package

### ISSUE THREAD

**Issue by Samgarr** [voxpupuli/puppet-prometheus#62]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.6
- Ruby: puppets very own ruby
- Distribution: Debian Jessie
- Module version: from master

## How to reproduce (e.g Puppet code you use)

```
 class { 'prometheus':                                                                                                                                                                                        
         install_method => 'package', 
         ...
```

## What are you seeing
> Sep 27 20:30:54 hostname systemd[2208]: Failed at step EXEC spawning /usr/local/bin/prometheus: No such file or directory

## What behaviour did you expect instead
If is "package" installation chosen, should be also used systemd service distributed with package.

## Any additional information you'd like to impart

If 'package' method is chosen, module still using own service which make prometheus not run. And without modules own service 'prometheus.yam' is not loaded because default is 'prometheus.yml'. So, i'm missing something or is this not supported use case? Thanks!

**Comment by tuxmea** [comment]
@Samgarr can you please check whether the systemd unit files are still from package or from prometheus module?

**Comment by Samgarr** [comment]
Yes, still a issue. I can make pull requests, if somebody will test it :) Changes here https://github.com/voxpupuli/puppet-prometheus/compare/master...Samgarr:master

**Comment by bastelfreak** [comment]
@Samgarr can you create a pull request for this please? Besides this: We should fix the service files so they work in both cases.

**Comment by tuxmea** [comment]
there already is a PR in #100 which takes care on this.
