### ISSUE TITLE
keeping exporter versions up-to-date

### ISSUE THREAD

**Issue by saz** [voxpupuli/puppet-prometheus#666]
Right now, some exporters (e.g. node_exporter, memcached_exporter) are pretty old.

Maybe it's possible to create a task to check for newer versions? Or is there a better way to keep it updated?

**Comment by roock** [comment]
This could be archived by using Renovate Bot (using regex manager) or maybe Dependabot to automatically crate PR if new versions of dependencies are released.

**Comment by TheMeier** [comment]
I have a good idea how to do that with renovate, how would you do that with dependabot @roock ?

**Comment by roock** [comment]
@TheMeier sorry, I don't know how this could be implemented with dependabot, I just wanted to express, from what I know about dependabot, it might be possible that this could also be implemented with dependabot  I usually use renovate bot for dependency management.

**Comment by saz** [comment]
Looks like as if @pccibot is taking care of that now.

**Comment by TheMeier** [comment]
Well I am trying with renovate and @pccibot. There is still a couple of open issues though. Most of them might actually lead to deprecations.
However I think the major point of this issue is addressed now. Do you agree @saz ?

**Comment by saz** [comment]
Looks good to me! Thanks for the work, I'll close this issue
