### ISSUE TITLE
module uses deprecated legacy function `has_keys`

### ISSUE THREAD

**Issue by marszip** [voxpupuli/puppet-prometheus#677]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.24
- Ruby: 2.7
- Distribution:
- Module version:

## What are you seeing

This module still uses a legacy function in config.pp on line 262, has_keys is deprecated.

Remove deprecated has_key function https://github.com/puppetlabs/puppetlabs-stdlib/pull/1319 ([MartyEwings](https://github.com/MartyEwings))

```
Note: Deprecated since Puppet 4.0.0, this can now be achieved in the Puppet
language with the following equivalent expression:

    $my_hash = {'key_one' => 'value_one'}
    if 'key_one' in $my_hash {
      notice('this will be printed')
    }
```

**Comment by zilchms** [comment]
seems this was adressed in #678 so i am closing this issue for now
