### ISSUE TITLE
Get rid of puppet 5 and lower artifacts

### ISSUE THREAD

**Issue by zilchms** [voxpupuli/puppet-prometheus#688]
Somewhere along the line of dropping puppet 5 support, some codefragments explicitely for puppet 5 and lower have remained untouched.
One example: https://github.com/voxpupuli/puppet-prometheus/blob/3ba0d85218a26c4d72257d7686276239ed2f74f0/manifests/config.pp#L222
We should find all of such instances and get rid of them.

**Comment by TheMeier** [comment]
This is the only instance I could find.

**Comment by zilchms** [comment]
Could very well be the only instance, just stumbled into it and thought I should keep a record on this :P
