### ISSUE TITLE
Extend Readme

### ISSUE THREAD

**Issue by 030** [voxpupuli/puppet-prometheus#7]
- Background
  why this monitoring tool
  How does this work (server - agent)?
  The config resides in /etc/prometheus/prometheus.yaml - http://localhost:9090
  link to the project https://prometheus.io/docs/introduction/overview/
- Usage
  some classes are not explained in the readme
  How to configure an alert? example?

**Comment by brutus333** [comment]
I improved a bit the README file. However, I do not plan to duplicate Prometheus documentation in this puppet module.
Does this solve the issue?

**Comment by brutus333** [comment]
Since no feedback received, I'll close the issue/
