### ISSUE TITLE
node_expoerter v0.15.0

### ISSUE THREAD

**Issue by TheMeier** [voxpupuli/puppet-prometheus#70]
The release 0.15.0 of node collector changes the configuration of the collectors..

> [CHANGE] Replace --collectors.enabled with per-collector flags #640

https://github.com/prometheus/node_exporter/pull/640

this renders all handling as it currently is implemented of the collectors in this module useless

also https://github.com/voxpupuli/puppet-prometheus/issues/33  is propably obsoleted by this

**Comment by bastelfreak** [comment]
Hi @TheMeier, thanks for the notify. Are you able to provide a PR for this?

**Comment by TheMeier** [comment]
@bastelfreak actually i was considering to do so this weekend....
