### ISSUE TITLE
Received SIGTERM, exiting gracefully

### ISSUE THREAD

**Issue by jerome2710** [voxpupuli/puppet-prometheus#712]
A former employee of us setup Prometheus through Puppet for our servers. Unfortunately, it seems that Alertmanager keeps stopping, preventing us from receiving alerts. This creates a problem, where we are not automatically notified of issues anymore.

![Scherm­afbeelding 2024-03-15 om 12 16 12](https://github.com/voxpupuli/puppet-prometheus/assets/4600095/0bb07313-13a2-4d33-8f86-fb53672c3267)

 I am not super familiar with Puppet,  but know a thing or two about our servers. Does anyone know what could be causing our dead alertmanager instance? I tried restarting it several times, but it somehow stops every time.

**Comment by TheMeier** [comment]
The probability is very slim that this has anything to do with the puppet module. `Received SIGTERM, exiting gracefully...` means the process received the TERM signal for some reason. Maybe something else is running on that node, that intentionally stops the service.

Maybe running alertmanager with `--log.level=debug` gives you some more info. Also please post module version, operating system and the relevant puppet code you are using.

**Comment by TheMeier** [comment]
Looking at it again, it even says `systemd[1]: Stopping Prometheus Aletmanager` ~8 seconds after its was started.

**Comment by TheMeier** [comment]
Closing due to lack of feedback. Please re-open if you think this is an issue that still needs to be addressed here
